export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

//login

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';